In [1]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
file_to_load = "C:\\Users\\Thomas Byrne\\Documents\\purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

In [2]:
purchase_df = pd.DataFrame(purchase_data)

In [3]:
purchase_df.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [4]:
total_players = pd.DataFrame({"Total Players": [purchase_df["Purchase ID"].count()]})

In [5]:
total_players

   Total Players
0            780

In [6]:
unique_items = purchase_df["Item Name"].nunique()
avg_price = purchase_df["Price"].mean()
total_purchases = purchase_df["Purchase ID"].count()
revenue = purchase_df["Price"].sum()
pd.options.display.float_format = '${:,.2f}'.format
summary_df  = pd.DataFrame({"Number of Unique Items": [unique_items], "Average Price": [avg_price],
                            "Number of Purchases": [total_purchases], "Total Revenue": [revenue]})

In [7]:
summary_df.head()

   Number of Unique Items  Average Price  Number of Purchases  Total Revenue
0                     179          $3.05                  780      $2,379.77

In [8]:
gender_total = purchase_df["Gender"].value_counts()
percents = purchase_df['Gender'].value_counts(normalize=True) * 100
pd.options.display.float_format = '{:,.2f}%'.format
gender_count = pd.DataFrame({"Total Count": gender_total, "Percentage of Players": percents})
gender_count

                       Total Count  Percentage of Players
Male                           652                 83.59%
Female                         113                 14.49%
Other / Non-Disclosed           15                  1.92%

In [9]:
gender_df = purchase_df.groupby("Gender")
gender_avg = gender_df["Price"].mean()
gender_price = gender_df["Price"].sum()
unique_df = purchase_df.drop_duplicates("SN")
unique = unique_df["Gender"].value_counts()
avg_per_person = gender_price / unique
pd.options.display.float_format = '${:,.2f}'.format
gender_sort_df = pd.DataFrame({"Total Count": gender_total, "Average Purchase Price": gender_avg,
                                "Total Purchase Price": gender_price, 
                                "Average Purchase Price per Person": avg_per_person})
gender_sort_df

,Total Count,Average Purchase Price,Total Purchase Price,Average Purchase Price per Person
Female,113,$3.20,$361.94,$4.47
Male,652,$3.02,"$1,967.64",$4.07
Other / Non-Disclosed,15,$3.35,$50.19,$4.56

In [10]:
unique

Male                     484
Female                    81
Other / Non-Disclosed     11
Name: Gender, dtype: int64

In [118]:
bins = [1, 10, 14, 15, 20, 25, 30, 35, 40]
labels = ['<10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40+']
age_df = purchase_df.groupby('Age')
age_cut = pd.cut(age_df['Age'], bins=bins, labels=labels)
age_total = pd.cut(age_df['Age'], bins=bins).value_counts()
percents = pd.cut(age_df['Age'], bins=bins).value_counts(normalize=True) * 100
age_cut = age_cut.drop_duplicates('first')
age_cut = age_cut.dropna(how='any')
total_df = pd.DataFrame({'Age': age_cut, 'Total Count': age_total.values, 'Percentage of Players': percents.values})

ValueError: setting an array element with a sequence.

In [117]:
age_df.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53%
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56%
2,2,Ithergue48,24,Male,92,Final Critic,4.88%
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27%
4,4,Iskosia90,23,Male,131,Fury,1.44%
5,5,Yalae81,22,Male,81,Dreamkiss,3.61%
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18%
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67%
8,8,Undjask33,22,Male,21,Souleater,1.10%
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58%
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74%
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67%
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18%
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70%
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86%
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89%
16,16,Lisirra25,20,Male,40,Second Chance,2.52%
17,17,Zontibe81,21,Male,161,Devine,1.76%
18,18,Reunasu60,22,Female,82,Nirvana,4.90%
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64%
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60%
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48%
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81%
23,23,Eyrian71,40,Male,151,Severance,3.40%
24,24,Siala43,30,Male,141,Persuasion,3.19%
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23%
26,26,Lirtossa84,11,Male,71,Demise,1.61%
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09%
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32%
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16%
...,...,...,...,...,...,...,...
449,449,Ethralista69,13,Male,34,Retribution Axe,2.22%
474,474,Ina92,31,Male,145,Fiery Glass Crusader,4.58%
477,477,Mindossa76,41,Male,173,Stormfury Longsword,4.93%
480,480,Salilis27,40,Male,59,"Lightning, Etcher of the King",4.23%
481,481,Sondossa69,7,Male,179,"Wolf, Promise of the Moonwalker",4.48%
486,486,Eurithphos97,9,Male,53,Vengeance Cleaver,2.05%
487,487,Raillydeu47,14,Male,93,Apocalyptic Battlescythe,1.97%
489,489,Jiskimsda56,28,Male,32,Orenmir,1.14%
493,493,Chanirrasta87,14,Male,139,"Mercy, Katana of Dismay",4.94%
516,516,Aidain51,39,Female,35,Heartless Bone Dualblade,3.45%
517,517,Aerithnuphos61,39,Male,128,"Blazeguard, Reach of Eternity",4.91%
531,531,Lirtirra81,12,Male,143,Frenzied Scimitar,1.56%
539,539,Eosurdru76,11,Male,117,"Heartstriker, Legacy of the Light",1.79%
541,541,Aesri53,31,Male,161,Devine,1.76%
546,546,Sondadar26,9,Male,159,"Oathbreaker, Spellblade of Trials",3.08%
553,553,Yadam35,28,Male,2,Verdict,2.48%
557,557,Frichaya88,42,Male,8,"Purgatory, Gem of Regret",3.93%
563,563,Isri34,38,Male,142,Righteous Might,2.62%
575,575,Sondadar26,9,Male,137,"Aetherius, Boon of the Blessed",3.39%
601,601,Ilastilis78,11,Male,93,Apocalyptic Battlescythe,1.97%
606,606,Nitherian58,28,Male,123,Twilight's Carver,2.28%
648,648,Eustyria89,39,Male,150,Deathraze,2.85%
659,659,Lisassasda39,36,Male,140,Striker,2.94%
672,672,Ililsan66,9,Male,122,Unending Tyranny,2.85%
674,674,Aeral68,43,Male,77,"Piety, Guardian of Riddles",4.00%
692,692,Quaecjask96,9,Male,78,"Glimmer, Ender of the Moon",4.40%
728,728,Chanosiaya39,44,Male,93,Apocalyptic Battlescythe,1.97%
738,738,Eusur90,36,Male,121,Massacre,1.60%
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23%
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70%

In [112]:
bins = [1, 10, 14, 15, 20, 25, 30, 35, 40]
labels = ['<10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40+']
age_cut = pd.cut(purchase_df['Age'], bins=bins, labels=labels)
age_total = pd.cut(purchase_df['Age'], bins=bins).value_counts()